version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/application
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: ngx
    networks:
      - xdebug

  app:
    build:
      context: ./
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www/application
      - ./_docker/app/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=server"
    container_name: app
    networks:
      - xdebug

networks:
  xdebug:
    driver: bridge
